spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/code2
    username: root
    password: 123456
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: classpath:/templates/.html
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.csy.test.entity
